server:
  port: 8080

jwt:
  secret: syllabicate31231412312321314231231241241231231234124123
  expiration: 86400000

spring:
  datasource:
    url: jdbc:postgresql://dpg-cqtcgulds78s739jdn7g-a.singapore-postgres.render.com:5432/health_care_jl2l
    username: health_care_jl2l_user
    password: 7hnfw6YAA5k4mYgo5w78QaBqfA625OP6
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        physical_naming_strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy